### ISSUE TITLE
Use selector text in basket and reciept

### ISSUE THREAD

**Issue by lindeloev** [giveffektivt/donation-platform#17]
If I select "Vores anbefaling (GiveWell Top Charities Fund)", it shows "GiveWell Maximum Impact Fund" in the basket and the receipt email. I propose that we simply use the drop-down text across the board. 

Especially these days to make it clear that you're first and foremost earmarking to a *purpose* and then we pick an *organization* to do it :-)

![image](https://user-images.githubusercontent.com/1439417/190961104-2965a028-9832-4f2f-8e4e-6c8e3efb40aa.png)

**Comment by maximbaz** [comment]
Agreed to keep the basket text without org name, otherwise done 👍
