### ISSUE TITLE
Outlook does not support styling of <div> tags

### ISSUE THREAD

**Issue by AsgerSP** [giveffektivt/donation-platform#21]
The width of the email templates is not respected in Outlook because the templates uses <div>s

It seems like a general issue for Outlook and the most common solution proposed is changes to a <table> structure instead of using <div>s for the email templates. I have tried in emailonacid to get this to work, but unfortunately without success. 
Not sure how big a change it would be to make the switch.

Some inspiration can be found here:
https://www.emailonacid.com/blog/article/email-development/how-to-code-emails-for-outlook-2016/

**Comment by maximbaz** [comment]
Fixed, thanks @AsgerSP!
