### ISSUE TITLE
Measure counterfactuals donations

### ISSUE THREAD

**Issue by mikolajkniejski** [giveffektivt/donation-platform#4]
add one more step asking the user to say if he donated to givewell charities before

**Comment by mikolajkniejski** [comment]
>Also, trying to measure counterfactual donations is really hard and susceptible to finicky definitions. In the beginning, we were also concerned with measuring counterfactual donations, but in the end I don't expect this to be that useful (with one exception*) because 1) Knowing the percentage of counterfactual donations isn't really decision relevant. You still want to optimize for growth. 2) Growth solves nearly everything (https://playbook.samaltman.com/#growth). If you grow enough you can safely assume that most of your new donors is of your working.

>*The exception is that in the beginning you, and the funders covering your expenses, would like to make sure that the counterfactual amount exceeds the operations costs or - again - that the growth rate is sufficiently large that it soon will. If so, you can be confident that you will break even and then I'll suggest you stop spending limited resources (that could have been used for further growth) on measuring counterfactual donations.

**Comment by lindeloev** [comment]
@mikolajkniejski, nice. What is the source?

**Comment by mikolajkniejski** [comment]
Jorgen
