### ISSUE TITLE
Validate CPR

### ISSUE THREAD

**Issue by lindeloev** [giveffektivt/donation-platform#46]
We can validate CPR numbers in TypeScript to reduce the error rate 10-30 fold. Here's some example code: https://codepen.io/netsi1964/pen/MaJvaW

You can read more about how CPR numbers are built here: http://kode.tingeling.dk/cpr_fix/. According to this source, very few (!) people have CPR numbers that do not conform to this checking, but they will probably be used to this obstacle pretty much everywhere.

**Comment by maximbaz** [comment]
Given that CPR.dk itself [strongly suggests](https://cpr.dk/cpr-systemet/personnumre-uden-kontrolciffer-modulus-11-kontrol) not making online lives of those people even harder than they probably already are, I would prefer to not put extra obstacles to people who want to be done with the form... 

We could however run the validation, and on failure not mark the field with a blocking red border, but instead show some message like "Your CPR number looks invalid, double check it", and allow the user to proceed with the form... What do you think?

**Comment by lindeloev** [comment]
I fully agree with that approach, @maximbaz. Thanks!

**Comment by lindeloev** [comment]
BTW, the code I linked to doesn't seem to include the check of the first of the four last integers. It's not crucial IMO.

**Comment by maximbaz** [comment]
Note for future self: we should also validate whether a give day and month combo are even possible, i.e. highligh `999999-9996` as invalid CPR despite the correct modulus11 check.
