### ISSUE TITLE
Bank transfer warning around new year

### ISSUE THREAD

**Issue by lindeloev** [giveffektivt/donation-platform#47]
Should we add a text in the bank-transfer confirmation (email + web) the last 5-6 days of the year, saying something like this in red or otherwise highlighted?

    Husk at starte overførslen inden nytår, hvis du vil have fradraget i år. Du kan evt. bruge straksoverførsel, hvis nødvendigt.

I'm just presenting the idea here for discussion. We should probably polish this a bit if we choose to implement it.

**Comment by maximbaz** [comment]
Implemented :+1:
