### ISSUE TITLE
Different font in donation form and website 

### ISSUE THREAD

**Issue by mikolajkniejski** [giveffektivt/donation-platform#51]
![image](https://user-images.githubusercontent.com/64133041/230729494-a7b50e6b-67fa-4b90-8edb-e91b4bf3bae1.png)

It would probably look more consistent if you used the same font every where.

**Comment by maximbaz** [comment]
This has luckily be solved for a while after moving to Framer (though membership signup still needs to be migrated, but that is a separate story).
