### ISSUE TITLE
Make subscription via MobilePay work

### ISSUE THREAD

**Issue by lindeloev** [giveffektivt/donation-platform#7]
... or throw a more helpful error message that subscriptions are not possible using MobilePay :-) 

When subscribing (on https://donation-platform.vercel.app/) using MobilePay, I get this error:

![image](https://user-images.githubusercontent.com/1439417/167566508-d457a457-05f6-4195-b1a2-48962d9de46f.png)

**Comment by maximbaz** [comment]
MobilePay subscriptions are live in production, at last 🎉
